name: Deploy

on:
  push:
    branches:
    - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install Trunk
        run: |
          curl -Lo trunk https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu
          chmod +x trunk
          sudo mv trunk /usr/local/bin/
      - name: Trunk Build
        run: trunk build --release --public-url "/vtolvr-radar/"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
